In [2]:
# utilizar os Dataframes do Pandas para manipular as instâncias
import pandas as pd
import numpy as np
# matplotlib e seaborn para visualizar
import matplotlib.pyplot as plt
import seaborn as sns
# gdown para baixar os dados
import gdown
plt.style.use('ggplot')

In [ ]:
url = 'https://drive.google.com/file/d/1YcovsHNhRveU0EeMwlASYaflIA3fSwh2/view?usp=drive_link'
output = 'filmes.jsonl'
gdown.download(url=url, output=output, quiet=False)

In [3]:
df = pd.read_json('filmes.jsonl', lines=True)

In [4]:
df.head()

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count,credits
0,False,/uTqxyztRGHSq96JYhByyNFuqqld.jpg,None,62000000,"[{'id': 878, 'name': 'Ficção científica'}, {'i...",,8202,tt0402022,[US],en,...,92,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,O Futuro é Flux.,Aeon Flux,False,5.640,2561,"{'cast': [{'adult': False, 'gender': 1, 'id': ..."
1,False,/2PYSbjodqH6ytgXaeDtWitFjK1l.jpg,"{'id': 384142, 'name': 'Animal: Coleção', 'pos...",0,"[{'id': 28, 'name': 'Ação'}, {'id': 18, 'name'...",,10252,tt0437072,[US],en,...,93,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,Animal,False,5.700,50,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
2,False,/iujJbAcLr7FdXeqSgWz4NKwzzKt.jpg,None,70000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",,20496,tt0346457,[IN],hi,...,150,False,"[{'english_name': 'Hindi', 'iso_639_1': 'hi', ...",Released,,O Motim,False,6.000,74,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."
3,False,/dhr0q4eiRr8ltqPig32TwhPRdaD.jpg,None,0,"[{'id': 27, 'name': 'Terror'}, {'id': 53, 'nam...",,17,tt0411267,[GB],en,...,87,False,"[{'english_name': 'Welsh', 'iso_639_1': 'cy', ...",Released,,Escuridão,False,5.667,300,"{'cast': [{'adult': False, 'gender': 1, 'id': ..."
4,False,/3XQBmsJtO3iK76pZyiJn4a2djpr.jpg,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",,45072,tt0386751,"[CA, US, GB]",en,...,99,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,,Mistério em River King,False,5.800,76,"{'cast': [{'adult': False, 'gender': 2, 'id': ..."

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10500 entries, 0 to 10499
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  10500 non-null  bool
 1   backdrop_path          10496 non-null  str
 2   belongs_to_collection  2318 non-null   object
 3   budget                 10500 non-null  int64
 4   genres                 10500 non-null  object
 5   homepage               10500 non-null  str
 6   id                     10500 non-null  int64
 7   imdb_id                10500 non-null  str
 8   origin_country         10500 non-null  object
 9   original_language      10500 non-null  str
 10  original_title         10500 non-null  str
 11  overview               10500 non-null  str
 12  popularity             10500 non-null  float64
 13  poster_path            10500 non-null  str
 14  production_companies   10500 non-null  object
 15  production_countries   10500 non-null  object
 16  release_date           10500 non-null  str
 17  revenue                10500 non-null  int64
 18  runtime                10500 non-null  int64
 19  softcore               10500 non-null  bool
 20  spoken_languages       10500 non-null  object
 21  status                 10500 non-null  str
 22  tagline                10500 non-null  str
 23  title                  10500 non-null  str
 24  video                  10500 non-null  bool
 25  vote_average           10500 non-null  float64
 26  vote_count             10500 non-null  int64
 27  credits                10500 non-null  object
dtypes: bool(3), float64(2), int64(5), object(7), str(11)
memory usage: 2.0+ MB

In [6]:
df.drop(columns=['backdrop_path','homepage','belongs_to_collection', 'poster_path','status','adult'], inplace=True)

In [9]:
# Retorna o total de linhas onde o budget é igual a 0
(df['budget'] == 0).sum()

np.int64(4999)

In [10]:
df = df[df['budget'] != 0]
df.info()

<class 'pandas.DataFrame'>
Index: 5501 entries, 0 to 10497
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                5501 non-null   int64
 1   genres                5501 non-null   object
 2   id                    5501 non-null   int64
 3   imdb_id               5501 non-null   str
 4   origin_country        5501 non-null   object
 5   original_language     5501 non-null   str
 6   original_title        5501 non-null   str
 7   overview              5501 non-null   str
 8   popularity            5501 non-null   float64
 9   production_companies  5501 non-null   object
 10  production_countries  5501 non-null   object
 11  release_date          5501 non-null   str
 12  revenue               5501 non-null   int64
 13  runtime               5501 non-null   int64
 14  softcore              5501 non-null   bool
 15  spoken_languages      5501 non-null   object
 16  tagline               5501 non-null   str
 17  title                 5501 non-null   str
 18  video                 5501 non-null   bool
 19  vote_average          5501 non-null   float64
 20  vote_count            5501 non-null   int64
 21  credits               5501 non-null   object
dtypes: bool(2), float64(2), int64(5), object(6), str(7)
memory usage: 913.3+ KB

In [ ]:
top_5_rows = df.nlargest(5, 'revenue')[['title', 'revenue']]
top_5_popular_rows = df.nlargest(5, 'popularity')[['title', 'popularity']]
print(top_5_rows)
print(top_5_popular_rows)

                                 title     revenue
7118              Vingadores: Ultimato  2925713609
2386                            Avatar  2923706026
8714         Avatar: O Caminho da Água  2334484620
10377     Ne Zha 2: O Renascer da Alma  2270700370
5331   Star Wars: O Despertar da Força  2068223624
                                         title  popularity
8420   Resident Evil: Bem-Vindo a Raccoon City    176.9048
4533                           Antes de Dormir    101.2734
10206                               Zootopia 2     93.2525
7118                      Vingadores: Ultimato     92.3413
10043                      A Guerra dos Mundos     89.1389

In [ ]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,1.050000e+04,1.050000e+04,10500.000000,1.050000e+04,10500.000000,10500.000000,10500.000000
mean,1.758138e+07,3.721334e+05,7.140377,4.836887e+07,104.363810,6.404122,1472.214095
std,3.864917e+07,3.666239e+05,6.811491,1.507449e+08,19.523313,0.844756,3006.462957
min,0.000000e+00,1.700000e+01,1.641500,0.000000e+00,1.000000,2.000000,50.000000
25%,0.000000e+00,4.150325e+04,3.586975,0.000000e+00,92.000000,5.900000,184.000000
50%,1.000000e+06,2.905750e+05,4.958000,9.321050e+05,101.000000,6.422000,435.000000
75%,1.750000e+07,5.854112e+05,7.965225,2.625140e+07,114.000000,7.000000,1321.250000
max,6.588000e+08,1.600028e+06,176.904800,2.925714e+09,467.000000,9.300000,41428.000000